### PR TITLE
Properly import jasmineRequire object before using

### PR DESCRIPTION
**Pull request by amilligan**
I've been working through the process of getting Jasmine up and running with a Rails 6 project using webpack.  I'm no webpack expert, but I quickly learned that webpack is very aggressive at isolating JS code in separate files.  That means spec files have to actually import/require the files containing the code under test, which then means that Jasmine really has to be compiled by webpack.  So, I create a Jasmine pack, and I ran into the dreaded 'jasmineRequire is not defined' error.

I found this referenced in #1377 and #1280 without resolution.  I haven't looked at those issues in great detail, but I believe it's clear that this problem originates in Jasmine, not the calling libraries.  The beginning of the problem lies in the definition of `jasmineRequire` in **jasmine.js**:

```javascript
  if (typeof module !== 'undefined' && module.exports && typeof exports !== 'undefined') {
    ...
    jasmineRequire = exports;
  } else {
    ...
    jasmineRequire = jasmineGlobal.jasmineRequire = {};
  }
```
In old, asset pipeline world this just tacks `jasmineRequire` onto the global object (window), and other files access it all higgledy piggledy from there; no worries.  But, in new, webpack world, this assigns `jasmineRequire` as the export from the file, available to other files that _require_ this file.  At pack compile time the global objects assigned to `window` don't appear to be available to other files.

The files **jasmine-html.js** and **boot.js** both reference `jasmineRequire` without requiring the **jasmine.js** file which defines it, assuming it exists in the global scope.  Hence the missing reference, the failure to load, and general worldwide unhappiness.  The solution, as presented here, is simply to have those two files require **jasmine.js** in the case that `window.jasmineRequire` is not available.

I've made this change locally and Jasmine loads happily.  Peace and prosperity return to all the land.

@ragaskar 
@infews 
@slackersoft

### CODE REVIEW

**Comment by ragaskar** [comment]
Hi Adam: I don't really do any Jasmine maintaining anymore (you def. want @slackersoft ) -- but thought I'd say hi! 

Hope you're well, and thanks for the PR. :)

**Comment by amilligan** [comment]
@ragaskar Hey Rajan, I figured as much.  But, your face is still indelibly imprinting on my memory when I think of Jasmine.  And it has been a long time, so I figured I'd take the opportunity to say hi as well.  If you find yourself back in New York at any point you should let me buy you a drink.

**Comment by amilligan** [comment]
I added one more small commit, with related changes.  The **boot.js** file was extending all of the Jasmine methods into `window`, which, as mentioned, doesn't work with Webpack.  This simply uses the `getGlobal` method that the Jasmine core object provides to get the appropriate global object for the given environment and extend the methods into that.  In non-Webpack scenarios the `getGlobal` method should return `window`, so nothing should change.

I think there's something to be said for not polluting the global namespace, but providing a top-level object to kick off each spec block.  RSpec made this change a while ago, and other than the necessity of adding `RSpec.describe` at the top level it didn't cause much disruption.  But, that's beyond the scope of this change; something to consider in the future.

Incidentally, these changes are in service of working through https://github.com/jasmine/jasmine-gem/issues/311.

@slackersoft

**Comment by slackersoft** [comment]
Thanks for taking a crack at this. I've looked into mechanisms for not polluting the global namespace, but I haven't had time to really sit down and figure out how to properly `export` various Jasmine top level concepts without breaking the existing non-webpack way to write your tests. We don't get anything as easy as `Rspec.describe` with just `it` inside because JavaScript doesn't have allow calling member functions without `this`. I want to try running this against some browsers here too before I merge it in.

**Comment by amilligan** [comment]
@slackersoft Sure, of course, the idea about not polluting the global namespace was just an aside. I struggled with the same thing in Objective C.  I don't recall finding a particularly satisfying solution for Cedar, so I can't imagine it will be trivial.  Perhaps it's not even possible. 
 Nothing's ever as easy as it is in Ruby, sadly.

**Comment by stoivo** [comment]
I have tested and this seem good

**Comment by sgravrock** [comment]
Thanks, @amilligan . I merged this in d04b813 but Github isn't showing the PR as merged.

**Pull request closed without merging**
