### PR TITLE
Fix missing comma on bower.json

### PR DESCRIPTION
**Pull request by gabrielhpugliese**
I've just installed it in my project and suddenly stopped working. Now I think it's fixed.

### CODE REVIEW

**Comment by pecota** [comment]
:+1:

**Comment by joshuacc** [comment]
:+1:

**Comment by slackersoft** [comment]
Sorry about this. We're not sure how this ever worked since I forgot that comma when I created the file in the first place.

**Comment by slackersoft** [comment]
We just released a 2.2.1 for bower that contains the merged fix. Please let us know if there are any other issues.

**Pull request merged**
