### PR TITLE
fix the environment issue and add a jasmine-core.standalone.js

### PR DESCRIPTION
**Pull request by wood1986**
#1377

### CODE REVIEW

**Comment by wood1986** [comment]
Here is the bug example https://github.com/wood1986/jasmine-bug-example

**Comment by sgravrock** [comment]
I'm seeing a few issues with this pull request as it stands now, particularly the lack of tests, but before we go into that I think it's worth talking about what it's for. From the issue that you linked to I understand that you're trying to include Jasmine via Webpack. Can you give us some information on why you want to do that rather than just including the Jasmine JS files via script tags in your spec runner HTML? There's an ongoing labor cost to supporting additional environments like Webpack, and I want to make sure we're spending future maintainer time wisely.

**Comment by wood1986** [comment]
1. The problem is the standalone setting can be done by the `webpack`. Then you don't need to hardcode the version in your tailor-made html to run the standalone page.

2. As I try to wire them up the standalone setting and `webpack`, it gives the #1377 but it can be fixed by using `script-loader`. I think this is a hack not the correct fix.

3. I believe the the root cause of #1377 is that the existing environment checking is not enough

4. It just cost you 30 seconds or less to update `jasmine-core.standalone.js`. Actually you do not need to supporting the additional environment.

**Comment by wood1986** [comment]
any update?

**Comment by slackersoft** [comment]
I still don't think this is a Jasmine issue, so much as a CommonJS/WebPack concern, considering that [gulp-jasmine-browser](https://github.com/jasmine/gulp-jasmine-browser) work [with webpack](https://github.com/jasmine/gulp-jasmine-browser/#usage-with-webpack) without any modifications to Jasmine itself.

Additionally, you've named your new boot file `jasmine.standalone.js` but it has nothing to do with the standalone-ness of the Jasmine environment, but rather the usage of CommonJS and WebPack.

I don't think this is something we're looking to change in Jasmine at this time. Thanks for using Jasmine!

**Pull request closed without merging**
