### PR TITLE
fix for #1906: add url pathName in toQueryString function

### PR DESCRIPTION
**Pull request by jlpstolwijk**
## Description
ToQueryString function

## Motivation and Context
See [issue #1906 ](https://github.com/jasmine/jasmine/issues/1906)

## How Has This Been Tested?
Ran specs in local environment.

## Types of changes

- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x ] I have read the **CONTRIBUTING** document.
- [ x] I have added tests to cover my changes.
- [ x] All new and existing tests passed.

### CODE REVIEW

**Comment by sgravrock** [comment]
Could you please add a test for this and a comment in the code mentioning why the path has to be included in the URL?

**Comment by jlpstolwijk** [comment]
Sorry for the delay. I just added a comment and a test, could you have a look again? Thank you!

**Comment by sgravrock** [comment]
You can fix the Prettier issues by running `npm run cleanup` and committing the result. Other than that, this looks good. Thanks.

**Comment by jlpstolwijk** [comment]
Somehow, npm run cleanup did not work - prettier was using a different config locally or something. But right-clicking in VS code en "format with... prettier" did the job. Thanks in advance for merging!

**Pull request merged**
