### PR TITLE
Add toHaveLength matcher

### PR DESCRIPTION
**Pull request by emilos**
## Description

Thanks for the lib :+1:

I've added an additional matcher called `toHaveLength` which can be helpful for arrays and strings.

## Motivation and Context

Minor utility for length checking. In my use case it would also makes it easier to switch from `jest` to `jasmine`.

The matcher could be extended to support any object that has a length property, I didn't add it because I'm not sure it's that would be a common use case.

## How Has This Been Tested?

`npm t -s`

## Types of changes

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by sgravrock** [comment]
Can you help me understand the benefit of this matcher over using `toEqual` on the length, besides Jest compatibility?

**Comment by emilos** [comment]
1)

```js
expect(user.id).toEqual(1)
expect(user.guid.length).toEqual(32)
```

vs

```js
expect(user.id).toEqual(1)
expect(user.guid).toHaveLength(32)
```

2)

```js
let { id, guid } = user
expect(id).toEqual(1)
expect(guid.length).toEqual(32)
```

```js
let { id, guid } = user
expect(id).toEqual(1)
expect(guid).toHaveLength(32)
```

It's not a big difference, I find the second one easier a little bit faster to understand at a quick glance.

**Comment by slackersoft** [comment]
Jasmine does support [custom matchers](https://jasmine.github.io/edge/custom_matcher.html) if you want to add this globally to your suite to aid in conversion for now. I'm not sure a `toHaveLength` matcher is something we're looking for in Jasmine core at this time. It's a bit specific, and easily implementable in a suite that feels the need for it.

Hope this helps. Thanks for using Jasmine!

**Comment by emilos** [comment]
Thanks, that's fine. I think that the lib would be a little bit easier to adopt in more places if the core api would be a little bit broader, but that's a very opinionated measure :). There are matchers available like `toBeCloseTo` or `toBeGreaterThanOrEqual` which imo have the same or least probability of usage than the one presented above.

Thanks again, closing then :)

**Pull request closed without merging**
