### PR TITLE
To have been called times

### PR DESCRIPTION
**Pull request by logankd**
Pull request for https://github.com/jasmine/jasmine/issues/853 feature request.

I started, but I have a few questions 
* I wasn't sure how to call toHaveBeenCalledTimes from toHaveBeenCalledOnce (I added the once for convenience. So I ended copying and pasting....
* Can I stop them from using .not? It doesn't really make sense in this instance.

### CODE REVIEW

**Comment by logankd** [comment]
I ran those tests, but I'll look at it again since if failed.

**Comment by logankd** [comment]
Any plans to make a release to get this and other fixes out the door?

**Comment by slackersoft** [comment]
I had hoped to get some more time to do some serious feature dev soon and get a real 2.4 out, but it's looking like there are quite a few features and fixes since the last release. I'm going to take a look at some other stuff and try to get a release out this week.

**Comment by logankd** [comment]
I still think it would be great to have a release with the 62 commits that are outstanding. I understand if you are too busy though. It seems as if Jasmine is stalling out :-(.

**Comment by logankd** [comment]
I added documentation: https://github.com/jasmine/jasmine.github.io/issues/51

**Pull request closed without merging**
