### PR TITLE
PrettyPrinter survives if objects throw in toString

### PR DESCRIPTION
**Pull request by johnjbarton**
## Description
Add a test that fails demonstrating that toBe does not work if the objects have a faulty toString().

### CODE REVIEW

**Comment by johnjbarton** [comment]
Now with a fix

**Comment by elliot-nelson** [comment]
Out of curiosity, what's the real-life use case for this?  Did you run into a third party lib that has a toString() that raises an exception?

**Comment by johnjbarton** [comment]
The real-life case was objects with references to objects created by code generation.

**Comment by slackersoft** [comment]
Given the part of the matcher being affected here, this seems like the error is actually coming from the PrettyPrinter. I would expect _every_ other matcher in Jasmine to have the same issue as `toBe` does here. We should instead fix this in the PrettyPrinter itself instead of in each of the individual matchers that has a message built.

In the PrettyPrinter, we can probably even return a somewhat reasonable fallback in the case that a provided `toString` throws an error. (Like the base level formatter).

Hope this helps. Thanks for using Jasmine!

**Pull request merged**
