### PR TITLE
Allow 0 as an expected argument for toHaveBeenCalledTimes

### PR DESCRIPTION
**Pull request by logankd**
Allow 0 as an argument to fix #871 and added a test.

### CODE REVIEW

**Comment by logankd** [comment]
Fix for issue #1018

**Comment by logankd** [comment]
@slackersoft or anyone else. I can't see why that build failed. The test passed locally for me and on all but phantom and the bash script. If anyone could give me a pointer, I'd appreciate it.

**Comment by slackersoft** [comment]
The end result looks fairly good, but there are a couple issues we need to be fixed before we merge this pull request:

* Please smash your commits down to a single commit
* Undo the formatting change that changed all of the indentation of the spec file

**Comment by logankd** [comment]
I wasn't sure how to smash the commits, so I took the other way and created a separate pull request #1048.

**Comment by logankd** [comment]
@slackersoft thanks for taking the time to look at this.

**Pull request closed without merging**
