### PR TITLE
Implement spies for get/set functions on accessor properties 

### PR DESCRIPTION
**Pull request by celluj34**
This PR is a rebased version of #1008 against the current master branch of jasmine/jasmine, SHA 8624a52ee0b6f13b3b608ea6417ccc02257c5412.

I have proposed this to hopefully get this feature into base, fixing the merge conflicts, as the original PR author has not yes updated his PR.

### CODE REVIEW

**Comment by celluj34** [comment]
@smacker, @brunoskonrad, @henrahmagix, @gantaa, @erwinverdonk, I have rebased the old PR. Let me know if there's anything else that should be done.

**Comment by henrahmagix** [comment]
👍 nice one @celluj34

**Comment by henrahmagix** [comment]
Now either can be merged; I hope one is :)

**Comment by erwinverdonk** [comment]
@celluj34 Thank you so much for making this new PR without conflicts. Truly appreciated!

**Comment by vchu-vr** [comment]
Is there a timeline for merging?

**Comment by celluj34** [comment]
@slackersoft Can you take a look at this? There are many people that would love to see this merged, myself included. Let us know if there's anything else that needs to be done.

**Comment by henrahmagix** [comment]
Thanks @slackersoft!

**Comment by sgruhier** [comment]
when will be the next release with this PR?

**Comment by Narretz** [comment]
This is in 2.6, but are there any docs for this?

**Comment by slackersoft** [comment]
The docs are here: http://localhost:4000/api/edge/global.html#spyOnProperty

**Comment by celluj34** [comment]
localhost?

**Comment by slackersoft** [comment]
Sorry, I must have grabbed the wrong tab. Try this: https://jasmine.github.io/api/edge/global.html#spyOnProperty

**Comment by celluj34** [comment]
Neat. Thanks!

**Pull request merged**
