### PR TITLE
allow adding a deprecation object

### PR DESCRIPTION
**Pull request by UziTech**
## Description

Allow `jasmine.getEnv().deprecated() to take an error object instead of a string

## Motivation and Context

Trying to add a deprecation with an error object so I can use it's stack instead of the the `deprecationWarning.stack` starting at `env.deprecated`

## How Has This Been Tested?

added integration test

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

I tried running `grunt buildDistribution` but it gave me the error `Warning: not found: bundle Use --force to continue.`

### CODE REVIEW

**Comment by sgravrock** [comment]
PhantomJS doesn't set the `stack` property of error objects until they're thrown. The error objects in the code under test are thrown but the ones in the test are not, so the latter's `stack` values are null and the comparison fails.

**Comment by slackersoft** [comment]
Additionally, Travis-CI only runs the Node.js and PhantomJS branches because the real browsers all require SauceLabs and thus secure environment variables, and are thus as disabled as we can make them for PRs.

I would also like to hear a bit more about why you need this functionality. The `deprecated` method isn't really intended for usage outside of Jasmine-Core as it more a way to mark certain features of Jasmine as deprecated.

**Comment by UziTech** [comment]
I maintain [`atom-jasmine2-test-runner`](https://github.com/UziTech/atom-jasmine2-test-runner) and have been looking for a way to list [deprecations](https://github.com/UziTech/atom-jasmine2-test-runner/blob/master/lib/spec-helper/deprecations.js#L50) in Atom without showing them as errors.

I just thought it would be useful to combine the `deprecationWarnings` in Jasmine with the deprecations in Atom. Atom already has a way to list deprecations but when I use `env.deprecated` the stack trace points to the `env.deprecated` call instead of the deprecation in Atom.

**Comment by UziTech** [comment]
Any chance we can backport this to 2.99.x?

**Comment by slackersoft** [comment]
The whole point of the 2.99 release(s) is to help people upgrade to 3.0. They aren't really intended for long term usage. I'm inclined to just leave it in 3.0 and try to help everyone update to a version we're going to support with further development. Sorry.

**Comment by UziTech** [comment]
Sounds good. Thanks for the response.

**Pull request merged**
