### PR TITLE
Fix tests for `toEqual` diff output in IE

### PR DESCRIPTION
**Pull request by benchristel**
This fixes spec failures in IE caused by https://github.com/jasmine/jasmine/pull/1163

### CODE REVIEW

**Comment by benchristel** [comment]
Hi @slackersoft, please review when you have a chance.

It seems the IE tests are not actually being run on Travis for pending PRs, which would have caught this before the first PR was merged. Any reason the IE tests run for master but not for other branches?

**Comment by slackersoft** [comment]
Unfortunately, none of the browser tests are run for pull requests. The way it's set up now we use SauceLabs for the browser tests, so we have our API info secured travis environment variables, which [aren't available to pull request builds](https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml) for security reasons.

**Comment by benchristel** [comment]
Ahh, that makes sense. Thanks for the info.

**Comment by slackersoft** [comment]
Merged

**Pull request closed without merging**
