### PR TITLE
remove eval to create wrapper

### LINKED ISSUE #1325: 2.6.0 Breaks CSP in Atom
`EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'"`

UziTech/atom-jasmine2-test-runner#14

### PR DESCRIPTION
**Pull request by UziTech**
fixes #1325

### CODE REVIEW

**Comment by slackersoft** [comment]
It looks to me like this will effectively revert #1055 as spies will no longer have the same arity as the function they are replacing. I'd be happy to talk through ways to solve this without `eval`.

**Comment by UziTech** [comment]
I am hoping to figure out a way to do it with the functions to keep their arity

**Comment by glebec** [comment]
[Like I said](https://github.com/jasmine/jasmine/pull/1055#issuecomment-196168851) in the original issue, [Sinon uses hard-coded functions](https://github.com/sinonjs/sinon/blob/2c89183415ad34f1627dc87094dd88bc1e57b2f2/lib/sinon/spy.js#L78) as a workaround to avoid `eval`.

We looked at this pretty carefully and it seemed like the only possible solutions were either hard-coded functions or `eval`. Maybe with modern (e.g. ES2015) use of metaprogramming tools there's some new trick out there, but I don't know offhand.

**Comment by UziTech** [comment]
we could use `defineProperty` if all of the supported platforms support it

```javascript
Object.defineProperty(wrapper, "length", { value: numArgs });
```

Otherwise hard coded functions will have to do.

**Comment by slackersoft** [comment]
IE 8 only supports `defineProperty` onDOM nodes, so we'll have to stick with hardcoded functions for now

**Pull request closed without merging**
